/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ProgressDashboardPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_PROGRESS = "progress-dashboard-view";
var DEFAULT_DATA = {
  manualProgress: {},
  customSkills: [],
  attachedNotes: {},
  excludedNotes: {},
  deletedSkills: [],
  pinnedCategories: [],
  skillStartDates: {},
  skillEndDates: {}
};
function parseChildren(desc) {
  if (!desc)
    return null;
  const parts = desc.split(/[、，,]/).map((s) => s.trim()).filter((s) => s.length > 0 && !isOnlyPunct(s));
  if (parts.length >= 2)
    return parts;
  return null;
}
function isOnlyPunct(s) {
  return /^[\s\-—、，,()（）]+$/.test(s);
}
function getSkillKey(parent, name) {
  return parent ? `${parent}/${name}` : name;
}
var ProgressDashboardPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.data = DEFAULT_DATA;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_PROGRESS,
      (leaf) => new ProgressDashboardView(leaf, this)
    );
    this.addCommand({
      id: "open-progress-dashboard",
      name: "打开学习项目进度看板",
      callback: () => this.activateView()
    });
    this.addRibbonIcon("bar-chart-3", "学习项目进度看板", () => {
      this.activateView();
    });
  }
  async onunload() {
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.data = Object.assign({}, DEFAULT_DATA, loaded);
    const seenNames = /* @__PURE__ */ new Set();
    const uniqueCustomSkills = [];
    for (const cs of this.data.customSkills) {
      if (!cs || !cs.name)
        continue;
      if (seenNames.has(cs.name))
        continue;
      seenNames.add(cs.name);
      uniqueCustomSkills.push(cs);
    }
    this.data.customSkills = uniqueCustomSkills;
    if (!this.data.manualProgress)
      this.data.manualProgress = {};
    if (!this.data.customSkills)
      this.data.customSkills = [];
    if (!this.data.attachedNotes)
      this.data.attachedNotes = {};
    if (!this.data.excludedNotes)
      this.data.excludedNotes = {};
    if (!this.data.deletedSkills)
      this.data.deletedSkills = [];
    if (!this.data.pinnedCategories)
      this.data.pinnedCategories = [];
    if (!this.data.skillStartDates)
      this.data.skillStartDates = {};
    if (!this.data.skillEndDates)
      this.data.skillEndDates = {};
    if (this.data.skillDates) {
      for (const [k, v] of Object.entries(this.data.skillDates)) {
        if (v && !this.data.skillStartDates[k]) {
          this.data.skillStartDates[k] = v;
        }
      }
      delete this.data.skillDates;
    }
    const uniquePinned = [];
    const seenCats = /* @__PURE__ */ new Set();
    for (const cat of this.data.pinnedCategories) {
      if (!seenCats.has(cat)) {
        seenCats.add(cat);
        uniquePinned.push(cat);
      }
    }
    this.data.pinnedCategories = uniquePinned;
    await this.saveSettings();
  }
  async saveSettings() {
    await this.saveData(this.data);
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_PROGRESS);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({
      type: VIEW_TYPE_PROGRESS,
      active: true
    });
    this.app.workspace.revealLeaf(leaf);
  }
};
var ProgressDashboardView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.sortMode = "progress-desc";
    this.entries = [];
    this.expandedSkills = /* @__PURE__ */ new Set();
    this.searchQuery = "";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_PROGRESS;
  }
  getDisplayText() {
    return "学习项目进度看板";
  }
  getIcon() {
    return "bar-chart-3";
  }
  async onOpen() {
    this.renderView();
  }
  async onClose() {
    const cleanup = this._viewCleanup;
    if (cleanup && Array.isArray(cleanup)) {
      for (const fn of cleanup) {
        try {
          fn();
        } catch (e) {
        }
      }
      this._viewCleanup = [];
    }
  }
  matchesSearch(entry, query) {
    if (!query)
      return true;
    if (entry.name.toLowerCase().includes(query))
      return true;
    if (entry.desc.toLowerCase().includes(query))
      return true;
    return false;
  }
  filterEntries(entries, query) {
    if (!query)
      return entries;
    return entries.map((entry) => {
      const nameMatch = this.matchesSearch(entry, query);
      const matchingChildren = entry.children.filter((c) => this.matchesSearch(c, query));
      if (nameMatch) {
        return entry;
      }
      if (matchingChildren.length > 0) {
        return { ...entry, children: matchingChildren };
      }
      return null;
    }).filter((e) => e !== null);
  }
  async renderView() {
    const container = this.contentEl;
    container.empty();
    container.addClass("progress-dashboard");
    this.entries = this.buildEntries();
    const header = container.createDiv("pd-header");
    header.createEl("h2", { text: "学习项目进度看板" });
    const flatEntries = this.flattenEntries();
    const stats = this.calcStats(flatEntries);
    const statsBar = container.createDiv("pd-stats");
    this.renderStat(statsBar, "总技能", String(stats.count), "var(--text-normal)");
    this.renderStat(statsBar, "平均进度", stats.avg + "%", this.getColorByProgress(stats.avg));
    this.renderStat(statsBar, "已完成", String(stats.completed), "#00e676");
    this.renderStat(statsBar, "进行中", String(stats.inProgress), "#00b0ff");
    this.renderStat(statsBar, "刚起步", String(stats.started), "#ff9100");
    this.renderStat(statsBar, "未开始", String(stats.notStarted), "var(--text-faint)");
    const toolbar = container.createDiv("pd-toolbar");
    toolbar.createEl("span", { cls: "pd-sort-label", text: "排序：" });
    const sortSelect = toolbar.createEl("select", { cls: "pd-sort-select" });
    const options = [
      { value: "progress-desc", text: "进度（高→低）" },
      { value: "progress-asc", text: "进度（低→高）" },
      { value: "name-asc", text: "名称（A→Z）" }
    ];
    for (const opt of options) {
      const el = sortSelect.createEl("option", { value: opt.value, text: opt.text });
      if (opt.value === this.sortMode)
        el.selected = true;
    }
    sortSelect.addEventListener("change", () => {
      this.sortMode = sortSelect.value;
      this.renderView();
    });
    const refreshBtn = toolbar.createEl("button", { cls: "pd-refresh-btn", text: "刷新" });
    refreshBtn.addEventListener("click", () => this.renderView());
    const searchInput = toolbar.createEl("input", { cls: "pd-search-input", attr: { placeholder: "搜索技能…" } });
    searchInput.value = this.searchQuery;
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value.toLowerCase().trim();
      this.renderView();
    });
    const addBtn = toolbar.createEl("button", { cls: "pd-add-btn", text: "+ 添加技能" });
    addBtn.addEventListener("click", () => {
      new AddSkillModal(this.app, (name, desc, category) => {
        console.log("[ProgressDashboard] 添加技能:", { name, desc, category });
        console.log("[ProgressDashboard] 当前 entries:", this.entries.map((e) => e.name));
        console.log("[ProgressDashboard] customSkills:", this.plugin.data.customSkills);
        console.log("[ProgressDashboard] deletedSkills:", this.plugin.data.deletedSkills);
        const exists = this.entries.some((e) => e.name === name && !e.parentName);
        if (exists) {
          new import_obsidian.Notice("该技能已存在：" + name);
          return;
        }
        this.plugin.data.customSkills.push({ name, desc, category });
        const skillKey = getSkillKey(null, name);
        if (this.plugin.data.deletedSkills.includes(skillKey)) {
          this.plugin.data.deletedSkills = this.plugin.data.deletedSkills.filter(
            (k) => k !== skillKey
          );
        }
        this.plugin.saveSettings();
        console.log("[ProgressDashboard] 保存后 customSkills:", this.plugin.data.customSkills);
        this.renderView();
        new import_obsidian.Notice("已添加技能：" + name);
      }).open();
    });
    const resetBtn = toolbar.createEl("button", { cls: "pd-reset-btn", text: "重置" });
    resetBtn.title = "清除所有数据";
    resetBtn.addEventListener("click", () => {
      new ConfirmModal(this.app, "重置看板", "确定要重置所有数据吗？\n这将清除所有进度、自定义技能、笔记关联等数据。\n（不会删除硬盘上的笔记文件）", () => {
        this.plugin.data.manualProgress = {};
        this.plugin.data.attachedNotes = {};
        this.plugin.data.excludedNotes = {};
        this.plugin.data.customSkills = [];
        this.plugin.data.deletedSkills = [];
        this.plugin.data.pinnedCategories = [];
        this.plugin.data.skillStartDates = {};
        this.plugin.data.skillEndDates = {};
        this.plugin.saveSettings();
        this.renderView();
        new import_obsidian.Notice("已重置所有数据");
      }).open();
    });
    const allCategories = this.getAllCategories();
    const pinnedCats = new Set(this.plugin.data.pinnedCategories);
    allCategories.sort((a, b) => {
      const aPinned = pinnedCats.has(a.category) ? 0 : 1;
      const bPinned = pinnedCats.has(b.category) ? 0 : 1;
      return aPinned - bPinned;
    });
    for (const cat of allCategories) {
      let catEntries = this.entries.filter((e) => e.category === cat.category && !e.parentName);
      catEntries = this.filterEntries(catEntries, this.searchQuery);
      if (catEntries.length === 0)
        continue;
      const sorted = this.sortEntries(catEntries, this.sortMode);
      const catSection = container.createDiv("pd-category-section");
      if (pinnedCats.has(cat.category)) {
        catSection.addClass("pd-category-pinned");
      }
      const catHeader = catSection.createDiv("pd-category-header");
      catHeader.createEl("span", { cls: "pd-category-title", text: cat.category });
      const isCatPinned = pinnedCats.has(cat.category);
      const catPinBtn = catHeader.createEl("span", { cls: "pd-cat-pin-btn" + (isCatPinned ? " pd-pin-active" : "") });
      catPinBtn.title = isCatPinned ? "取消置顶分类" : "置顶分类";
      catPinBtn.innerHTML = `<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 17v5"/><path d="M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z"/></svg>`;
      catPinBtn.addEventListener("click", () => {
        if (isCatPinned) {
          this.plugin.data.pinnedCategories = this.plugin.data.pinnedCategories.filter((c) => c !== cat.category);
        } else {
          this.plugin.data.pinnedCategories.push(cat.category);
        }
        this.plugin.saveSettings();
        this.renderView();
      });
      const catStats = this.calcStats(catEntries);
      catHeader.createEl("span", {
        cls: "pd-category-stats",
        text: `${catStats.completed}/${catStats.count} 已完成 · 平均 ${catStats.avg}%`
      });
      const catList = catSection.createDiv("pd-list");
      for (const entry of sorted) {
        this.renderSkillRow(catList, entry, 0);
      }
    }
  }
  flattenEntries() {
    const result = [];
    for (const e of this.entries) {
      if (e.parentName)
        continue;
      result.push(e);
      for (const child of e.children) {
        result.push(child);
      }
    }
    return result;
  }
  renderStat(parent, label, value, color) {
    const item = parent.createDiv("pd-stat-item");
    item.createEl("span", { cls: "pd-stat-label", text: label });
    const val = item.createEl("span", { cls: "pd-stat-value", text: value });
    val.style.color = color;
  }
  renderSkillRow(parent, entry, depth) {
    const row = parent.createDiv("pd-row");
    if (depth > 0)
      row.addClass("pd-child-row");
    const skillKey = getSkillKey(entry.parentName, entry.name);
    row.setAttribute("data-skill-key", skillKey);
    if (!entry.parentName) {
      row.setAttribute("data-is-parent", "true");
    }
    const colName = row.createDiv("pd-col-name");
    const titleRow = colName.createDiv("pd-skill-title-row");
    if (entry.children.length > 0) {
      const toggle = titleRow.createEl("span", { cls: "pd-toggle" });
      const isExpanded = this.expandedSkills.has(getSkillKey(entry.parentName, entry.name));
      toggle.innerHTML = isExpanded ? `<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 12 15 18 9"/></svg>` : `<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 6 15 12 9 18"/></svg>`;
      toggle.addEventListener("click", (e) => {
        e.stopPropagation();
        const key = getSkillKey(entry.parentName, entry.name);
        if (this.expandedSkills.has(key)) {
          this.expandedSkills.delete(key);
        } else {
          this.expandedSkills.add(key);
        }
        this.renderView();
      });
    } else {
      titleRow.createEl("span", { cls: "pd-toggle-spacer" });
    }
    titleRow.createEl("span", { cls: "pd-skill-title", text: entry.name });
    const colBar = row.createDiv("pd-col-bar");
    const barTrack = colBar.createDiv("pd-bar-track");
    const barFill = barTrack.createDiv("pd-bar-fill");
    const pct = entry.progress;
    barFill.style.width = pct + "%";
    barFill.style.background = this.getGradientByProgress(pct);
    const handle = barTrack.createDiv("pd-bar-handle");
    handle.style.left = pct + "%";
    const pctEl = colBar.createDiv("pd-pct-inline");
    pctEl.setText(pct + "%");
    pctEl.style.color = this.getColorByProgress(pct);
    const levelBadge = colBar.createEl("span", { cls: "pd-level", text: this.getLevelText(pct) });
    levelBadge.className = "pd-level " + this.getLevelClass(pct);
    const updateUI = (clientX) => {
      const rect = barTrack.getBoundingClientRect();
      if (rect.width === 0)
        return entry.progress;
      let ratio = (clientX - rect.left) / rect.width;
      ratio = Math.max(0, Math.min(1, ratio));
      const newProgress = Math.round(ratio * 100);
      barFill.style.width = newProgress + "%";
      handle.style.left = newProgress + "%";
      pctEl.setText(newProgress + "%");
      pctEl.style.color = this.getColorByProgress(newProgress);
      levelBadge.setText(this.getLevelText(newProgress));
      levelBadge.className = "pd-level " + this.getLevelClass(newProgress);
      entry.progress = newProgress;
      entry.manualProgress = newProgress;
      return newProgress;
    };
    const saveProgress = async (newProgress) => {
      const key = getSkillKey(entry.parentName, entry.name);
      console.log("[ProgressDashboard] saveProgress:", {
        key,
        entryName: entry.name,
        parentName: entry.parentName,
        newProgress,
        hasChildren: entry.children.length
      });
      this.plugin.data.manualProgress[key] = newProgress;
      if (!entry.parentName) {
        this.plugin.data.manualProgress[entry.name] = newProgress;
      } else {
        this.plugin.data.manualProgress[`${entry.parentName}/${entry.name}`] = newProgress;
      }
      if (!entry.parentName && entry.children.length > 0) {
        for (const child of entry.children) {
          const childKey = getSkillKey(entry.name, child.name);
          this.plugin.data.manualProgress[childKey] = newProgress;
        }
      }
      if (entry.parentName) {
        this.updateParentProgress(entry.parentName);
        this.refreshParentUI(entry.parentName);
      }
      await this.plugin.saveSettings();
      console.log("[ProgressDashboard] manualProgress:", { ...this.plugin.data.manualProgress });
    };
    let isDragging = false;
    let rafId = null;
    let lastClientX = 0;
    barTrack.addEventListener("mousedown", (e) => {
      if (e.button !== 0)
        return;
      e.preventDefault();
      isDragging = true;
      lastClientX = e.clientX;
      updateUI(e.clientX);
    });
    const onMove = (e) => {
      if (!isDragging)
        return;
      e.preventDefault();
      lastClientX = e.clientX;
      if (rafId === null) {
        rafId = requestAnimationFrame(() => {
          rafId = null;
          updateUI(lastClientX);
        });
      }
    };
    const onUp = async (e) => {
      if (!isDragging)
        return;
      isDragging = false;
      if (rafId !== null) {
        cancelAnimationFrame(rafId);
        rafId = null;
      }
      const newProgress = updateUI(e.clientX);
      await saveProgress(newProgress);
    };
    document.addEventListener("mousemove", onMove, true);
    document.addEventListener("mouseup", onUp, true);
    const cleanup = () => {
      document.removeEventListener("mousemove", onMove, true);
      document.removeEventListener("mouseup", onUp, true);
      const id = rafId;
      if (id !== null)
        cancelAnimationFrame(id);
    };
    if (!this._viewCleanup)
      this._viewCleanup = [];
    this._viewCleanup.push(cleanup);
    const colNotes = row.createDiv("pd-col-notes");
    if (entry.files.length > 0) {
      for (const file of entry.files) {
        const noteChip = colNotes.createEl("span", { cls: "pd-note-chip" });
        noteChip.createEl("span", { cls: "pd-note-name", text: file.basename });
        const removeBtn = noteChip.createEl("span", { cls: "pd-note-remove" });
        removeBtn.innerHTML = `<svg viewBox="0 0 24 24" width="10" height="10" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>`;
        removeBtn.title = "从技能中移除此笔记";
        removeBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          console.log("[ProgressDashboard] removeNote:", { skillKey, filePath: file.path, fileName: file.basename });
          const keysToCheck = [skillKey, entry.name];
          if (entry.parentName)
            keysToCheck.push(entry.parentName);
          for (const key of keysToCheck) {
            const paths = this.plugin.data.attachedNotes[key];
            if (paths) {
              const idx = paths.indexOf(file.path);
              if (idx > -1) {
                paths.splice(idx, 1);
                if (paths.length === 0) {
                  delete this.plugin.data.attachedNotes[key];
                }
              }
            }
          }
          for (const [k, v] of Object.entries(this.plugin.data.attachedNotes)) {
            if (!keysToCheck.includes(k)) {
              const i = v.indexOf(file.path);
              if (i > -1) {
                v.splice(i, 1);
                if (v.length === 0) {
                  delete this.plugin.data.attachedNotes[k];
                }
              }
            }
          }
          for (const key of keysToCheck) {
            const excluded = this.plugin.data.excludedNotes[key] || [];
            if (!excluded.includes(file.path)) {
              excluded.push(file.path);
            }
            this.plugin.data.excludedNotes[key] = excluded;
          }
          const cache = this.app.metadataCache.getFileCache(file);
          if (cache && cache.frontmatter && cache.frontmatter["skill"]) {
            const yamlSkill = String(cache.frontmatter["skill"]).trim();
            const yamlExcluded = this.plugin.data.excludedNotes[yamlSkill] || [];
            if (!yamlExcluded.includes(file.path)) {
              yamlExcluded.push(file.path);
              this.plugin.data.excludedNotes[yamlSkill] = yamlExcluded;
            }
          }
          console.log("[ProgressDashboard] excludedNotes after remove:", { ...this.plugin.data.excludedNotes });
          await this.plugin.saveSettings();
          this.renderView();
        });
        noteChip.title = "点击打开：" + file.path + "（右键移除）";
        noteChip.addEventListener("click", (e) => {
          if (e.target === removeBtn || removeBtn.contains(e.target))
            return;
          e.stopPropagation();
          this.app.workspace.getLeaf(true).openFile(file);
        });
      }
    }
    const actionGroup = colNotes.createDiv("pd-action-group");
    if (!entry.parentName) {
      const addChildBtn = actionGroup.createEl("span", { cls: "pd-add-child-btn" });
      addChildBtn.title = "添加子技能";
      addChildBtn.innerHTML = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>`;
      addChildBtn.style.display = "none";
      row.addEventListener("mouseenter", () => {
        addChildBtn.style.display = "inline-flex";
      });
      row.addEventListener("mouseleave", () => {
        addChildBtn.style.display = "none";
      });
      addChildBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        const input = document.createElement("input");
        input.type = "text";
        input.placeholder = "输入子技能名称";
        input.style.padding = "6px 10px";
        input.style.borderRadius = "6px";
        input.style.border = "1px solid var(--interactive-accent)";
        input.style.background = "var(--background-secondary)";
        input.style.color = "var(--text-normal)";
        input.style.fontSize = "13px";
        input.style.width = "160px";
        actionGroup.replaceChild(input, addChildBtn);
        input.focus();
        const finishInput = (commit) => {
          const childName = input.value.trim();
          if (commit && childName) {
            const skillKey2 = getSkillKey(entry.name, childName);
            const exists = entry.children.some((c) => c.name === childName);
            if (exists) {
              new import_obsidian.Notice("子技能已存在：" + childName);
            } else {
              const newChild = {
                name: childName,
                desc: "",
                category: entry.category,
                progress: 0,
                manualProgress: null,
                noteProgress: null,
                files: [],
                hasNote: false,
                parentName: entry.name,
                children: []
              };
              let cs = this.plugin.data.customSkills.find((s) => s.name === entry.name);
              if (cs) {
                const existingChildren = parseChildren(cs.desc) || [];
                if (!existingChildren.includes(childName)) {
                  existingChildren.push(childName);
                  cs.desc = existingChildren.join("、");
                }
              } else {
                this.plugin.data.customSkills.push({
                  name: entry.name,
                  desc: childName,
                  category: entry.category
                });
              }
              this.expandedSkills.add(getSkillKey(entry.parentName, entry.name));
              this.plugin.saveSettings();
              new import_obsidian.Notice("已添加子技能：" + childName);
              this.renderView();
              return;
            }
          }
          actionGroup.replaceChild(addChildBtn, input);
        };
        input.addEventListener("keydown", (ev) => {
          if (ev.key === "Enter") {
            ev.preventDefault();
            finishInput(true);
          } else if (ev.key === "Escape") {
            ev.preventDefault();
            finishInput(false);
          }
        });
        input.addEventListener("blur", () => {
          finishInput(true);
        });
      });
    }
    if (entry.files.length === 0) {
      const createBtn = actionGroup.createEl("span", { cls: "pd-create-note-btn" });
      createBtn.title = "创建新笔记";
      createBtn.innerHTML = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="12" y1="18" x2="12" y2="12"/><line x1="9" y1="15" x2="15" y2="15"/></svg>`;
      createBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        try {
          const fileName = entry.name + ".md";
          const existing = this.app.vault.getAbstractFileByPath(fileName);
          if (existing) {
            await this.app.workspace.getLeaf(true).openFile(existing);
            return;
          }
          const skillYaml = entry.parentName ? `${entry.parentName}/${entry.name}` : entry.name;
          const frontmatter = `---
skill: ${skillYaml}
skill-progress: ${entry.progress}
---

# ${entry.name}

> 分类：${entry.category}
> 描述：${entry.desc}

## 学习记录

`;
          const newFile = await this.app.vault.create(fileName, frontmatter);
          await this.app.workspace.getLeaf(true).openFile(newFile);
          this.renderView();
        } catch (err) {
          new import_obsidian.Notice("创建笔记失败: " + String(err));
        }
      });
    }
    const attachBtn = actionGroup.createEl("span", { cls: "pd-attach-btn" });
    attachBtn.title = "添加已有笔记";
    attachBtn.innerHTML = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21.44 11.05l-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48"/></svg>`;
    attachBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      new PickNoteModal(this.app, this.plugin, skillKey, () => {
        this.renderView();
      }).open();
    });
    const startDate = this.plugin.data.skillStartDates[skillKey];
    const endDate = this.plugin.data.skillEndDates[skillKey];
    const createDateBtn = (type, value, title, icon) => {
      const btn = actionGroup.createEl("span", { cls: "pd-date-btn" });
      btn.title = title;
      const dateText = value ? `<span class="pd-date-text">${value.slice(5)}</span>` : "";
      btn.innerHTML = dateText + icon;
      btn.addEventListener("click", (e) => {
        e.stopPropagation();
        const input = document.createElement("input");
        input.type = "date";
        input.value = value || "";
        input.style.position = "absolute";
        input.style.opacity = "0";
        input.style.pointerEvents = "none";
        btn.appendChild(input);
        input.showPicker();
        input.addEventListener("change", async () => {
          if (type === "start") {
            if (input.value) {
              this.plugin.data.skillStartDates[skillKey] = input.value;
            } else {
              delete this.plugin.data.skillStartDates[skillKey];
            }
          } else {
            if (input.value) {
              this.plugin.data.skillEndDates[skillKey] = input.value;
            } else {
              delete this.plugin.data.skillEndDates[skillKey];
            }
          }
          await this.plugin.saveSettings();
          this.renderView();
        });
        input.addEventListener("blur", () => input.remove());
      });
      return btn;
    };
    const startIcon = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>`;
    const endIcon = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>`;
    createDateBtn("start", startDate, startDate ? "修改开始日期" : "添加开始日期", startIcon);
    createDateBtn("end", endDate, endDate ? "修改结束日期" : "添加结束日期", endIcon);
    const delBtn = actionGroup.createEl("span", { cls: "pd-del-btn" });
    delBtn.title = "删除此技能";
    delBtn.innerHTML = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-2 14a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/><path d="M9 6V4a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2"/></svg>`;
    delBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const skillK = getSkillKey(entry.parentName, entry.name);
      const keysToDelete = [skillK];
      if (entry.children.length > 0) {
        for (const child of entry.children) {
          const childKey = getSkillKey(entry.name, child.name);
          keysToDelete.push(childKey);
        }
      }
      for (const key of keysToDelete) {
        if (!this.plugin.data.deletedSkills.includes(key)) {
          this.plugin.data.deletedSkills.push(key);
        }
      }
      const newProgress = {};
      for (const [k, v] of Object.entries(this.plugin.data.manualProgress)) {
        if (!keysToDelete.includes(k)) {
          newProgress[k] = v;
        }
      }
      this.plugin.data.manualProgress = newProgress;
      const newAttached = {};
      for (const [k, v] of Object.entries(this.plugin.data.attachedNotes)) {
        if (!keysToDelete.includes(k)) {
          newAttached[k] = v;
        }
      }
      this.plugin.data.attachedNotes = newAttached;
      const newStartDates = {};
      for (const [k, v] of Object.entries(this.plugin.data.skillStartDates)) {
        if (!keysToDelete.includes(k)) {
          newStartDates[k] = v;
        }
      }
      this.plugin.data.skillStartDates = newStartDates;
      const newEndDates = {};
      for (const [k, v] of Object.entries(this.plugin.data.skillEndDates)) {
        if (!keysToDelete.includes(k)) {
          newEndDates[k] = v;
        }
      }
      this.plugin.data.skillEndDates = newEndDates;
      const isCustomSkill = this.plugin.data.customSkills.some((cs) => cs.name === entry.name);
      if (isCustomSkill && !entry.parentName) {
        this.plugin.data.customSkills = this.plugin.data.customSkills.filter(
          (cs) => cs.name !== entry.name
        );
      }
      this.plugin.saveSettings();
      this.renderView();
    });
    if (entry.children.length > 0) {
      const key = getSkillKey(entry.parentName, entry.name);
      const isExpanded = this.expandedSkills.has(key);
      if (isExpanded) {
        const childContainer = parent.createDiv("pd-children");
        for (const child of entry.children) {
          this.renderSkillRow(childContainer, child, depth + 1);
        }
      }
    }
  }
  getLevelText(pct) {
    if (pct >= 100)
      return "已完成";
    if (pct >= 67)
      return "冲刺中";
    if (pct >= 34)
      return "进行中";
    if (pct > 0)
      return "刚起步";
    return "未开始";
  }
  getLevelClass(pct) {
    if (pct >= 100)
      return "pd-level-done";
    if (pct >= 67)
      return "pd-level-high";
    if (pct >= 34)
      return "pd-level-mid";
    if (pct > 0)
      return "pd-level-low";
    return "pd-level-none";
  }
  updateParentProgress(parentName) {
    const parent = this.entries.find((e) => e.name === parentName && !e.parentName);
    if (!parent || parent.children.length === 0)
      return;
    const total = parent.children.reduce((sum, c) => sum + c.progress, 0);
    const avg = Math.round(total / parent.children.length);
    parent.progress = avg;
  }
  /* 拖动子技能时，实时更新父技能的进度条 UI（不重新渲染整个视图） */
  refreshParentUI(parentName) {
    const parent = this.entries.find((e) => e.name === parentName && !e.parentName);
    if (!parent)
      return;
    const parentRow = this.contentEl.querySelector(`[data-skill-key="${CSS.escape(parentName)}"][data-is-parent="true"]`);
    if (!parentRow)
      return;
    const barFill = parentRow.querySelector(".pd-bar-fill");
    const handle = parentRow.querySelector(".pd-bar-handle");
    const pctEl = parentRow.querySelector(".pd-pct-inline");
    const levelBadge = parentRow.querySelector(".pd-level");
    const pct = parent.progress;
    if (barFill) {
      barFill.style.width = pct + "%";
      barFill.style.background = this.getGradientByProgress(pct);
    }
    if (handle)
      handle.style.left = pct + "%";
    if (pctEl) {
      pctEl.setText(pct + "%");
      pctEl.style.color = this.getColorByProgress(pct);
    }
    if (levelBadge) {
      levelBadge.setText(this.getLevelText(pct));
      levelBadge.className = "pd-level " + this.getLevelClass(pct);
    }
  }
  buildEntries() {
    const noteMap = /* @__PURE__ */ new Map();
    const appAny = this.app;
    const vaults = [this.app.vault];
    if (appAny.vaults && Array.isArray(appAny.vaults)) {
      for (const v of appAny.vaults) {
        if (v !== this.app.vault)
          vaults.push(v);
      }
    }
    let allFiles = [];
    for (const v of vaults) {
      allFiles = allFiles.concat(v.getMarkdownFiles());
    }
    for (const file of allFiles) {
      const cache = this.app.metadataCache.getFileCache(file);
      if (!cache || !cache.frontmatter)
        continue;
      const skill = cache.frontmatter["skill"];
      if (!skill)
        continue;
      const skillName = String(skill).trim();
      if (!skillName)
        continue;
      const excludedPaths = this.plugin.data.excludedNotes[skillName];
      if (excludedPaths && excludedPaths.includes(file.path))
        continue;
      const progressRaw = cache.frontmatter["skill-progress"];
      let progressNum = 0;
      let hasProgress = false;
      if (progressRaw !== void 0 && progressRaw !== null) {
        const parsed = Number(progressRaw);
        if (!isNaN(parsed)) {
          progressNum = Math.max(0, Math.min(100, parsed));
          hasProgress = true;
        }
      }
      const existing = noteMap.get(skillName);
      if (existing) {
        existing.files.push(file);
        if (hasProgress) {
          existing.progress = progressNum;
          existing.hasExplicitProgress = true;
        }
      } else {
        noteMap.set(skillName, { progress: progressNum, files: [file], hasExplicitProgress: hasProgress });
      }
    }
    for (const [key, paths] of Object.entries(this.plugin.data.attachedNotes)) {
      let attFiles = [];
      const excludedPaths = this.plugin.data.excludedNotes[key] || [];
      for (const p of paths) {
        if (excludedPaths.includes(p))
          continue;
        const f = this.app.vault.getAbstractFileByPath(p);
        if (f && f instanceof import_obsidian.TFile)
          attFiles.push(f);
      }
      if (attFiles.length === 0)
        continue;
      const existing = noteMap.get(key);
      if (existing) {
        for (const f of attFiles) {
          if (!existing.files.some((ef) => ef.path === f.path)) {
            existing.files.push(f);
          }
        }
      } else {
        noteMap.set(key, { progress: 0, files: attFiles, hasExplicitProgress: false });
      }
    }
    const collectNoteData = (keys) => {
      let latest = null;
      const allFiles2 = [];
      let anyHasExplicit = false;
      let maxProgress = 0;
      for (const key of keys) {
        const data = noteMap.get(key);
        if (data) {
          for (const f of data.files) {
            if (!allFiles2.some((af) => af.path === f.path)) {
              allFiles2.push(f);
            }
          }
          if (data.hasExplicitProgress) {
            anyHasExplicit = true;
            if (data.progress > maxProgress)
              maxProgress = data.progress;
          }
          if (!latest || data.files[data.files.length - 1].stat.mtime > latest.file.stat.mtime) {
            latest = { progress: data.progress, file: data.files[data.files.length - 1], hasExplicitProgress: data.hasExplicitProgress };
          }
        }
      }
      if (allFiles2.length === 0)
        return null;
      return { progress: anyHasExplicit ? maxProgress : 0, files: allFiles2, hasExplicitProgress: anyHasExplicit };
    };
    const deletedSet = new Set(this.plugin.data.deletedSkills);
    const entries = [];
    for (const cs of this.plugin.data.customSkills) {
      const csKey = getSkillKey(null, cs.name);
      if (deletedSet.has(csKey))
        continue;
      const exists = entries.some((e) => e.name === cs.name && !e.parentName);
      if (exists)
        continue;
      const childrenNames = parseChildren(cs.desc);
      if (childrenNames) {
        const childEntries = childrenNames.map((childName) => {
          const childKey = getSkillKey(cs.name, childName);
          if (deletedSet.has(childKey))
            return null;
          const noteData = collectNoteData([childKey, childName]);
          const manual = this.plugin.data.manualProgress[childKey];
          let progress = 0;
          if (manual !== void 0)
            progress = manual;
          else if (noteData && noteData.hasExplicitProgress)
            progress = noteData.progress;
          return {
            name: childName,
            desc: "",
            category: cs.category,
            progress,
            manualProgress: manual !== void 0 ? manual : null,
            noteProgress: noteData ? noteData.progress : null,
            files: noteData ? noteData.files : [],
            hasNote: !!noteData,
            parentName: cs.name,
            children: []
          };
        }).filter((c) => c !== null);
        const total = childEntries.reduce((sum, c) => sum + c.progress, 0);
        const avg = childEntries.length > 0 ? Math.round(total / childEntries.length) : 0;
        const csManual = this.plugin.data.manualProgress[cs.name];
        entries.push({
          name: cs.name,
          desc: cs.desc,
          category: cs.category,
          progress: csManual !== void 0 ? csManual : avg,
          manualProgress: csManual !== void 0 ? csManual : null,
          noteProgress: null,
          files: [],
          hasNote: false,
          parentName: null,
          children: childEntries
        });
      } else {
        const noteData = collectNoteData([cs.name]);
        const manual = this.plugin.data.manualProgress[cs.name];
        let progress = 0;
        if (manual !== void 0) {
          progress = manual;
        } else if (noteData && noteData.hasExplicitProgress) {
          progress = noteData.progress;
        }
        entries.push({
          name: cs.name,
          desc: cs.desc,
          category: cs.category,
          progress,
          manualProgress: manual !== void 0 ? manual : null,
          noteProgress: noteData ? noteData.progress : null,
          files: noteData ? noteData.files : [],
          hasNote: !!noteData,
          parentName: null,
          children: []
        });
      }
    }
    for (const [skillName, data] of noteMap) {
      if (deletedSet.has(skillName))
        continue;
      let targetEntry = null;
      let isChild = false;
      targetEntry = entries.find((e) => e.name === skillName && !e.parentName) || null;
      if (!targetEntry) {
        for (const e of entries) {
          if (e.children.length > 0) {
            const child = e.children.find((c) => getSkillKey(e.name, c.name) === skillName);
            if (child) {
              targetEntry = child;
              isChild = true;
              break;
            }
            const parts = skillName.split("/");
            if (parts.length > 1 && e.name === parts[0]) {
              const childName = parts.slice(1).join("/");
              const childMatch = e.children.find((c) => c.name === childName);
              if (childMatch) {
                targetEntry = childMatch;
                isChild = true;
                break;
              }
            }
          }
        }
      }
      if (targetEntry) {
        targetEntry.files = data.files;
        targetEntry.hasNote = true;
        if (data.hasExplicitProgress) {
          targetEntry.noteProgress = data.progress;
        }
        if (targetEntry.manualProgress === null && data.hasExplicitProgress) {
          targetEntry.progress = data.progress;
        }
        if (!isChild && targetEntry.children.length > 0) {
          const total = targetEntry.children.reduce((sum, c) => sum + c.progress, 0);
          targetEntry.progress = targetEntry.manualProgress !== null ? targetEntry.manualProgress : Math.round(total / targetEntry.children.length);
        }
      }
    }
    return entries;
  }
  getAllCategories() {
    const cats = [];
    for (const cs of this.plugin.data.customSkills) {
      if (!cats.some((c) => c.category === cs.category)) {
        cats.push({ category: cs.category });
      }
    }
    if (this.entries.some((e) => e.category === "其他")) {
      if (!cats.some((c) => c.category === "其他")) {
        cats.push({ category: "其他" });
      }
    }
    return cats;
  }
  calcStats(entries) {
    const count = entries.length;
    const total = entries.reduce((sum, e) => sum + e.progress, 0);
    const avg = count > 0 ? Math.round(total / count) : 0;
    const completed = entries.filter((e) => e.progress >= 100).length;
    const inProgress = entries.filter((e) => e.progress >= 34 && e.progress < 100).length;
    const started = entries.filter((e) => e.progress > 0 && e.progress < 34).length;
    const notStarted = entries.filter((e) => e.progress === 0).length;
    return { count, avg, completed, inProgress, started, notStarted };
  }
  sortEntries(entries, mode) {
    const arr = [...entries];
    switch (mode) {
      case "progress-desc":
        arr.sort((a, b) => b.progress - a.progress);
        break;
      case "progress-asc":
        arr.sort((a, b) => a.progress - b.progress);
        break;
      case "name-asc":
        arr.sort((a, b) => a.name.localeCompare(b.name, "zh-CN"));
        break;
    }
    return arr;
  }
  getColorByProgress(p) {
    if (p >= 100)
      return "#00e676";
    if (p >= 67)
      return "#00b0ff";
    if (p >= 34)
      return "#ffc107";
    if (p > 0)
      return "#ff9100";
    return "var(--text-faint)";
  }
  getGradientByProgress(p) {
    if (p >= 100)
      return "linear-gradient(90deg, #00c853, #00e676)";
    if (p >= 67)
      return "linear-gradient(90deg, #0091ea, #00b0ff, #40c4ff)";
    if (p >= 34)
      return "linear-gradient(90deg, #ffa000, #ffc107, #ffe082)";
    if (p > 0)
      return "linear-gradient(90deg, #e65100, #ff9100, #ffab40)";
    return "transparent";
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, title, message, onConfirm) {
    super(app);
    this.title = title;
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("pd-modal");
    contentEl.createEl("h3", { text: this.title });
    const msgEl = contentEl.createEl("div");
    msgEl.style.marginBottom = "20px";
    msgEl.style.whiteSpace = "pre-line";
    msgEl.style.color = "var(--text-normal)";
    msgEl.style.fontSize = "14px";
    msgEl.textContent = this.message;
    const btnRow = contentEl.createDiv("pd-modal-btns");
    btnRow.style.display = "flex";
    btnRow.style.justifyContent = "flex-end";
    btnRow.style.gap = "10px";
    const cancelBtn = btnRow.createEl("button", { text: "取消" });
    cancelBtn.style.padding = "8px 16px";
    cancelBtn.style.borderRadius = "6px";
    cancelBtn.style.border = "1px solid var(--background-modifier-border)";
    cancelBtn.style.background = "var(--background-secondary)";
    cancelBtn.style.color = "var(--text-normal)";
    cancelBtn.style.cursor = "pointer";
    cancelBtn.addEventListener("click", () => this.close());
    const confirmBtn = btnRow.createEl("button", { text: "确定", cls: "mod-cta" });
    confirmBtn.style.padding = "8px 20px";
    confirmBtn.style.borderRadius = "6px";
    confirmBtn.style.border = "none";
    confirmBtn.style.background = "var(--interactive-accent)";
    confirmBtn.style.color = "var(--text-on-accent)";
    confirmBtn.style.fontWeight = "600";
    confirmBtn.style.cursor = "pointer";
    confirmBtn.addEventListener("click", () => {
      this.onConfirm();
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var AddSkillModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("pd-modal");
    contentEl.createEl("h3", { text: "添加技能" });
    const catRow = contentEl.createDiv("pd-form-row");
    catRow.style.marginBottom = "16px";
    catRow.createEl("label", { text: "分类" }).style.display = "block";
    this.categoryInput = catRow.createEl("input", {
      type: "text",
      placeholder: "输入分类名称，如：技术、学习、生活"
    });
    this.categoryInput.style.width = "100%";
    this.categoryInput.style.padding = "8px 12px";
    this.categoryInput.style.borderRadius = "6px";
    this.categoryInput.style.border = "1px solid var(--background-modifier-border)";
    this.categoryInput.style.background = "var(--background-secondary)";
    this.categoryInput.style.color = "var(--text-normal)";
    this.categoryInput.style.fontSize = "14px";
    this.categoryInput.style.boxSizing = "border-box";
    const nameRow = contentEl.createDiv("pd-form-row");
    nameRow.style.marginBottom = "16px";
    nameRow.createEl("label", { text: "技能名称" }).style.display = "block";
    this.nameInput = nameRow.createEl("input", {
      type: "text",
      placeholder: "输入技能/项目名称"
    });
    this.nameInput.style.width = "100%";
    this.nameInput.style.padding = "8px 12px";
    this.nameInput.style.borderRadius = "6px";
    this.nameInput.style.border = "1px solid var(--background-modifier-border)";
    this.nameInput.style.background = "var(--background-secondary)";
    this.nameInput.style.color = "var(--text-normal)";
    this.nameInput.style.fontSize = "14px";
    this.nameInput.style.boxSizing = "border-box";
    this.nameInput.addEventListener("input", () => {
    });
    const descRow = contentEl.createDiv("pd-form-row");
    descRow.style.marginBottom = "20px";
    descRow.createEl("label", { text: "技能描述" }).style.display = "block";
    const descHint = descRow.createEl("div", { text: "简要描述（可选）。用顿号/逗号分隔可拆为子技能" });
    descHint.style.fontSize = "12px";
    descHint.style.color = "var(--text-faint)";
    this.descInput = descRow.createEl("input", {
      type: "text",
      placeholder: "简要描述..."
    });
    this.descInput.style.width = "100%";
    this.descInput.style.padding = "8px 12px";
    this.descInput.style.borderRadius = "6px";
    this.descInput.style.border = "1px solid var(--background-modifier-border)";
    this.descInput.style.background = "var(--background-secondary)";
    this.descInput.style.color = "var(--text-normal)";
    this.descInput.style.fontSize = "14px";
    this.descInput.style.boxSizing = "border-box";
    const btnRow = contentEl.createDiv("pd-modal-btns");
    btnRow.style.display = "flex";
    btnRow.style.justifyContent = "flex-end";
    btnRow.style.gap = "10px";
    const cancelBtn = btnRow.createEl("button", { text: "取消" });
    cancelBtn.style.padding = "8px 16px";
    cancelBtn.style.borderRadius = "6px";
    cancelBtn.style.border = "1px solid var(--background-modifier-border)";
    cancelBtn.style.background = "var(--background-secondary)";
    cancelBtn.style.color = "var(--text-normal)";
    cancelBtn.style.cursor = "pointer";
    cancelBtn.addEventListener("click", () => this.close());
    const submitBtn = btnRow.createEl("button", {
      text: "添加",
      cls: "mod-cta"
    });
    submitBtn.style.padding = "8px 20px";
    submitBtn.style.borderRadius = "6px";
    submitBtn.style.border = "none";
    submitBtn.style.background = "var(--interactive-accent)";
    submitBtn.style.color = "var(--text-on-accent)";
    submitBtn.style.fontWeight = "600";
    submitBtn.style.cursor = "pointer";
    submitBtn.addEventListener("click", () => {
      const name = this.nameInput.value.trim();
      const desc = this.descInput.value.trim() || "自定义技能";
      const category = this.categoryInput.value.trim() || "自定义技能";
      if (!name) {
        new import_obsidian.Notice("请输入技能名称");
        this.nameInput.focus();
        return;
      }
      this.onSubmit(name, desc, category);
      this.close();
    });
    this.nameInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        submitBtn.click();
      }
    });
    this.descInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        submitBtn.click();
      }
    });
    this.nameInput.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PickNoteModal = class extends import_obsidian.Modal {
  constructor(app, plugin, skillKey, onPicked) {
    super(app);
    this.allFiles = [];
    this.sortMode = "time-desc";
    this.groupByFolder = true;
    this.folderGroups = /* @__PURE__ */ new Map();
    this.folderToggleState = /* @__PURE__ */ new Set();
    this.selectedPaths = /* @__PURE__ */ new Set();
    this.lastClickedPath = null;
    this.currentVisibleFiles = [];
    this.plugin = plugin;
    this.skillKey = skillKey;
    this.onPicked = onPicked;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("pd-modal");
    contentEl.createEl("h3", { text: "添加已有笔记到技能" });
    const toolbar = contentEl.createDiv("pd-pick-toolbar");
    toolbar.style.display = "flex";
    toolbar.style.alignItems = "center";
    toolbar.style.gap = "8px";
    toolbar.style.marginBottom = "10px";
    toolbar.style.flexWrap = "wrap";
    this.searchInput = toolbar.createEl("input", {
      type: "text",
      placeholder: "搜索笔记名称或路径...",
      cls: "pd-pick-search"
    });
    this.searchInput.style.flex = "1";
    this.searchInput.style.minWidth = "150px";
    this.searchInput.style.padding = "6px 10px";
    this.searchInput.style.borderRadius = "6px";
    this.searchInput.style.border = "1px solid var(--background-modifier-border)";
    this.searchInput.style.background = "var(--background-secondary)";
    this.searchInput.style.color = "var(--text-normal)";
    this.searchInput.style.fontSize = "13px";
    this.searchInput.style.boxSizing = "border-box";
    const sortLabel = toolbar.createEl("span", { text: "排序：" });
    sortLabel.style.fontSize = "12px";
    sortLabel.style.color = "var(--text-faint)";
    const sortSelect = toolbar.createEl("select");
    sortSelect.style.padding = "5px 8px";
    sortSelect.style.borderRadius = "6px";
    sortSelect.style.border = "1px solid var(--background-modifier-border)";
    sortSelect.style.background = "var(--background-secondary)";
    sortSelect.style.color = "var(--text-normal)";
    sortSelect.style.fontSize = "12px";
    sortSelect.style.cursor = "pointer";
    const opt1 = document.createElement("option");
    opt1.value = "time-desc";
    opt1.text = "修改时间↓";
    sortSelect.add(opt1);
    const opt2 = document.createElement("option");
    opt2.value = "time-asc";
    opt2.text = "修改时间↑";
    sortSelect.add(opt2);
    const opt3 = document.createElement("option");
    opt3.value = "name";
    opt3.text = "名称排序";
    sortSelect.add(opt3);
    sortSelect.value = this.sortMode;
    sortSelect.addEventListener("change", () => {
      this.sortMode = sortSelect.value;
      this.buildFolderGroups();
      this.renderList(this.searchInput.value.toLowerCase().trim());
    });
    const groupLabel = toolbar.createEl("span", { text: "按文件夹分组" });
    groupLabel.style.fontSize = "12px";
    groupLabel.style.color = "var(--text-faint)";
    groupLabel.style.display = "flex";
    groupLabel.style.alignItems = "center";
    groupLabel.style.gap = "4px";
    const groupCheckbox = toolbar.createEl("input", { type: "checkbox" });
    groupCheckbox.checked = this.groupByFolder;
    groupCheckbox.style.cursor = "pointer";
    groupCheckbox.addEventListener("change", () => {
      this.groupByFolder = groupCheckbox.checked;
      if (this.groupByFolder)
        this.buildFolderGroups();
      this.renderList(this.searchInput.value.toLowerCase().trim());
    });
    const selectAllBtn = toolbar.createEl("button", { text: "全选" });
    selectAllBtn.style.padding = "4px 10px";
    selectAllBtn.style.borderRadius = "6px";
    selectAllBtn.style.border = "1px solid var(--background-modifier-border)";
    selectAllBtn.style.background = "var(--background-secondary)";
    selectAllBtn.style.color = "var(--text-normal)";
    selectAllBtn.style.fontSize = "12px";
    selectAllBtn.style.cursor = "pointer";
    selectAllBtn.title = "全选当前显示的笔记";
    selectAllBtn.addEventListener("click", () => {
      for (const f of this.currentVisibleFiles) {
        const existing = this.plugin.data.attachedNotes[this.skillKey] || [];
        if (!existing.includes(f.path)) {
          this.selectedPaths.add(f.path);
        }
      }
      this.renderList(this.searchInput.value.toLowerCase().trim());
    });
    const invertBtn = toolbar.createEl("button", { text: "反选" });
    invertBtn.style.padding = "4px 10px";
    invertBtn.style.borderRadius = "6px";
    invertBtn.style.border = "1px solid var(--background-modifier-border)";
    invertBtn.style.background = "var(--background-secondary)";
    invertBtn.style.color = "var(--text-normal)";
    invertBtn.style.fontSize = "12px";
    invertBtn.style.cursor = "pointer";
    invertBtn.title = "反选当前显示的笔记";
    invertBtn.addEventListener("click", () => {
      for (const f of this.currentVisibleFiles) {
        const existing = this.plugin.data.attachedNotes[this.skillKey] || [];
        if (existing.includes(f.path))
          continue;
        if (this.selectedPaths.has(f.path)) {
          this.selectedPaths.delete(f.path);
        } else {
          this.selectedPaths.add(f.path);
        }
      }
      this.renderList(this.searchInput.value.toLowerCase().trim());
    });
    this.listEl = contentEl.createDiv("pd-pick-list");
    this.listEl.style.maxHeight = "400px";
    this.listEl.style.overflowY = "auto";
    this.listEl.style.border = "1px solid var(--background-modifier-border)";
    this.listEl.style.borderRadius = "8px";
    this.listEl.style.background = "var(--background-primary)";
    this.collectFiles();
    if (this.groupByFolder)
      this.buildFolderGroups();
    this.footerEl = contentEl.createDiv("pd-pick-footer");
    this.footerEl.style.display = "flex";
    this.footerEl.style.alignItems = "center";
    this.footerEl.style.justifyContent = "space-between";
    this.footerEl.style.marginTop = "10px";
    this.footerEl.style.padding = "10px";
    this.footerEl.style.background = "var(--background-secondary)";
    this.footerEl.style.borderRadius = "8px";
    const selectInfo = this.footerEl.createEl("span");
    selectInfo.style.fontSize = "12px";
    selectInfo.style.color = "var(--text-faint)";
    selectInfo.textContent = "已选择 0 个笔记";
    const btnContainer = this.footerEl.createDiv();
    btnContainer.style.display = "flex";
    btnContainer.style.gap = "8px";
    const clearBtn = btnContainer.createEl("button", { text: "清空选择" });
    clearBtn.style.padding = "6px 12px";
    clearBtn.style.borderRadius = "6px";
    clearBtn.style.border = "1px solid var(--background-modifier-border)";
    clearBtn.style.background = "var(--background-primary)";
    clearBtn.style.color = "var(--text-faint)";
    clearBtn.style.fontSize = "12px";
    clearBtn.style.cursor = "pointer";
    clearBtn.addEventListener("click", () => {
      this.selectedPaths.clear();
      this.renderList(this.searchInput.value.toLowerCase().trim());
    });
    this.confirmBtn = btnContainer.createEl("button", { text: "确认添加 (0)" });
    this.confirmBtn.style.padding = "6px 16px";
    this.confirmBtn.style.borderRadius = "6px";
    this.confirmBtn.style.border = "none";
    this.confirmBtn.style.background = "var(--interactive-accent)";
    this.confirmBtn.style.color = "var(--text-on-accent)";
    this.confirmBtn.style.fontSize = "13px";
    this.confirmBtn.style.fontWeight = "600";
    this.confirmBtn.style.cursor = "pointer";
    this.confirmBtn.style.opacity = "0.5";
    this.confirmBtn.addEventListener("click", () => {
      if (this.selectedPaths.size === 0)
        return;
      const current = this.plugin.data.attachedNotes[this.skillKey] || [];
      let added = 0;
      for (const path of this.selectedPaths) {
        if (!current.includes(path)) {
          current.push(path);
          added++;
        }
      }
      this.plugin.data.attachedNotes[this.skillKey] = current;
      this.plugin.saveSettings();
      new import_obsidian.Notice(`已关联 ${added} 个笔记`);
      this.onPicked();
      this.close();
    });
    this.renderList("");
    this.updateFooter();
    this.searchInput.addEventListener("input", () => {
      this.renderList(this.searchInput.value.toLowerCase().trim());
    });
    this.searchInput.focus();
  }
  updateFooter() {
    const count = this.selectedPaths.size;
    const info = this.footerEl.querySelector("span");
    if (info) {
      info.textContent = `已选择 ${count} 个笔记`;
    }
    this.confirmBtn.textContent = `确认添加 (${count})`;
    this.confirmBtn.style.opacity = count > 0 ? "1" : "0.5";
  }
  collectFiles() {
    const appAny = this.app;
    const vaults = [this.app.vault];
    if (appAny.vaults && Array.isArray(appAny.vaults)) {
      for (const v of appAny.vaults) {
        if (v !== this.app.vault)
          vaults.push(v);
      }
    }
    for (const v of vaults) {
      this.allFiles = this.allFiles.concat(v.getMarkdownFiles());
    }
  }
  buildFolderGroups() {
    this.folderGroups.clear();
    for (const file of this.allFiles) {
      const parts = file.path.split("/");
      const folderPath = parts.length > 1 ? parts.slice(0, -1).join("/") : "/";
      if (!this.folderGroups.has(folderPath)) {
        this.folderGroups.set(folderPath, []);
      }
      this.folderGroups.get(folderPath).push(file);
    }
    for (const [, files] of this.folderGroups) {
      this.sortFiles(files);
    }
  }
  sortFiles(files) {
    switch (this.sortMode) {
      case "time-desc":
        files.sort((a, b) => b.stat.mtime - a.stat.mtime);
        break;
      case "time-asc":
        files.sort((a, b) => a.stat.mtime - b.stat.mtime);
        break;
      case "name":
        files.sort((a, b) => a.basename.localeCompare(b.basename, "zh-CN"));
        break;
    }
  }
  hasSkillProperty(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    return !!(cache && cache.frontmatter && cache.frontmatter["skill"]);
  }
  formatDate(timestamp) {
    const date = new Date(timestamp * 1e3);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const oneDay = 24 * 60 * 60 * 1e3;
    if (diff < oneDay)
      return "今天";
    if (diff < 2 * oneDay)
      return "昨天";
    if (diff < 7 * oneDay)
      return `${Math.floor(diff / oneDay)}天前`;
    return `${date.getMonth() + 1}/${date.getDate()}`;
  }
  renderList(query) {
    this.listEl.empty();
    const existingPaths = new Set(this.plugin.data.attachedNotes[this.skillKey] || []);
    let filtered;
    if (query) {
      filtered = this.allFiles.filter(
        (f) => f.basename.toLowerCase().includes(query) || f.path.toLowerCase().includes(query)
      );
      this.sortFiles(filtered);
    } else {
      filtered = [...this.allFiles];
    }
    if (filtered.length === 0) {
      this.currentVisibleFiles = [];
      this.updateFooter();
      this.listEl.createDiv({
        text: "未找到笔记",
        cls: "pd-pick-empty"
      });
      return;
    }
    if (!query) {
      filtered.sort((a, b) => {
        const aHas = this.hasSkillProperty(a) ? 0 : 1;
        const bHas = this.hasSkillProperty(b) ? 0 : 1;
        if (aHas !== bHas)
          return aHas - bHas;
        if (this.sortMode === "time-desc")
          return b.stat.mtime - a.stat.mtime;
        if (this.sortMode === "time-asc")
          return a.stat.mtime - b.stat.mtime;
        return a.basename.localeCompare(b.basename, "zh-CN");
      });
    }
    this.currentVisibleFiles = filtered.filter(
      (f) => !existingPaths.has(f.path)
    );
    if (this.groupByFolder && !query) {
      this.renderGroupedList(filtered, existingPaths);
    } else {
      this.renderFlatList(filtered, existingPaths);
    }
    this.updateFooter();
  }
  renderGroupedList(files, existingPaths) {
    const groups = /* @__PURE__ */ new Map();
    for (const file of files) {
      const parts = file.path.split("/");
      const folderPath = parts.length > 1 ? parts.slice(0, -1).join("/") : "/";
      if (!groups.has(folderPath)) {
        groups.set(folderPath, []);
      }
      groups.get(folderPath).push(file);
    }
    for (const [, groupFiles] of groups) {
      groupFiles.sort((a, b) => {
        const aHas = this.hasSkillProperty(a) ? 0 : 1;
        const bHas = this.hasSkillProperty(b) ? 0 : 1;
        if (aHas !== bHas)
          return aHas - bHas;
        if (this.sortMode === "time-desc")
          return b.stat.mtime - a.stat.mtime;
        if (this.sortMode === "time-asc")
          return a.stat.mtime - b.stat.mtime;
        return a.basename.localeCompare(b.basename, "zh-CN");
      });
    }
    const sortedFolders = Array.from(groups.entries()).sort(([a], [b]) => {
      if (a === "/")
        return -1;
      if (b === "/")
        return 1;
      return a.localeCompare(b, "zh-CN");
    });
    for (const [folderPath, groupFiles] of sortedFolders) {
      const folderSection = this.listEl.createDiv("pd-pick-folder-section");
      folderSection.style.marginBottom = "8px";
      const folderHeader = folderSection.createDiv("pd-pick-folder-header");
      folderHeader.style.display = "flex";
      folderHeader.style.alignItems = "center";
      folderHeader.style.gap = "6px";
      folderHeader.style.padding = "6px 10px";
      folderHeader.style.background = "var(--background-secondary)";
      folderHeader.style.borderRadius = "6px";
      folderHeader.style.cursor = "pointer";
      folderHeader.style.userSelect = "none";
      folderHeader.style.transition = "background 0.15s";
      const folderIcon = folderHeader.createEl("span");
      const isExpanded = !this.folderToggleState.has(folderPath);
      folderIcon.innerHTML = isExpanded ? `<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 12 15 18 9"/></svg>` : `<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 6 15 12 9 18"/></svg>`;
      const displayName = folderPath === "/" ? "根目录" : folderPath;
      const folderNameEl = folderHeader.createEl("span", { text: displayName });
      folderNameEl.style.fontSize = "13px";
      folderNameEl.style.fontWeight = "600";
      folderNameEl.style.flex = "1";
      folderNameEl.style.overflow = "hidden";
      folderNameEl.style.textOverflow = "ellipsis";
      folderNameEl.style.whiteSpace = "nowrap";
      const count = folderHeader.createEl("span", { text: `${groupFiles.length}` });
      count.style.fontSize = "11px";
      count.style.color = "var(--text-faint)";
      count.style.background = "var(--background-modifier-border)";
      count.style.padding = "1px 6px";
      count.style.borderRadius = "10px";
      folderHeader.addEventListener("click", () => {
        if (this.folderToggleState.has(folderPath)) {
          this.folderToggleState.delete(folderPath);
        } else {
          this.folderToggleState.add(folderPath);
        }
        this.renderList(this.searchInput.value.toLowerCase().trim());
      });
      if (!isExpanded)
        continue;
      const fileList = folderSection.createDiv("pd-pick-file-list");
      fileList.style.paddingLeft = "16px";
      fileList.style.marginTop = "4px";
      for (const file of groupFiles) {
        this.createFileItem(fileList, file, existingPaths);
      }
    }
  }
  renderFlatList(files, existingPaths) {
    const withSkill = files.filter((f) => this.hasSkillProperty(f));
    const withoutSkill = files.filter((f) => !this.hasSkillProperty(f));
    if (withSkill.length > 0 && !this.searchInput.value) {
      const sectionLabel = this.listEl.createDiv();
      sectionLabel.style.padding = "6px 10px";
      sectionLabel.style.fontSize = "11px";
      sectionLabel.style.color = "var(--interactive-accent)";
      sectionLabel.style.fontWeight = "600";
      sectionLabel.style.background = "rgba(var(--interactive-accent-rgb), 0.08)";
      sectionLabel.style.borderBottom = "1px solid var(--background-modifier-border)";
      sectionLabel.textContent = `📋 已有技能关联的笔记（${withSkill.length}）`;
      for (const file of withSkill) {
        this.createFileItem(this.listEl, file, existingPaths);
      }
      const sectionLabel2 = this.listEl.createDiv();
      sectionLabel2.style.padding = "6px 10px";
      sectionLabel2.style.fontSize = "11px";
      sectionLabel2.style.color = "var(--text-faint)";
      sectionLabel2.style.fontWeight = "600";
      sectionLabel2.style.background = "var(--background-secondary)";
      sectionLabel2.style.borderBottom = "1px solid var(--background-modifier-border)";
      sectionLabel2.textContent = `📝 其他笔记（${withoutSkill.length}）`;
    }
    const filesToRender = this.searchInput.value ? files : withoutSkill.length > 0 ? withoutSkill : files;
    for (const file of filesToRender) {
      this.createFileItem(this.listEl, file, existingPaths);
    }
  }
  createFileItem(parent, file, existingPaths) {
    const isExisting = existingPaths.has(file.path);
    const isSelected = this.selectedPaths.has(file.path);
    const item = parent.createDiv("pd-pick-item");
    item.style.display = "flex";
    item.style.alignItems = "center";
    item.style.gap = "8px";
    item.style.padding = "6px 10px";
    item.style.cursor = isExisting ? "not-allowed" : "pointer";
    item.style.borderBottom = "1px solid var(--background-modifier-border)";
    item.style.fontSize = "13px";
    item.style.borderRadius = "4px";
    item.style.transition = "background 0.15s";
    item.setAttribute("data-path", file.path);
    if (isSelected) {
      item.style.background = "rgba(var(--interactive-accent-rgb), 0.15)";
      item.style.borderLeft = "3px solid var(--interactive-accent)";
    }
    const checkbox = item.createEl("input", { type: "checkbox" });
    checkbox.style.width = "16px";
    checkbox.style.height = "16px";
    checkbox.style.cursor = isExisting ? "not-allowed" : "pointer";
    checkbox.style.flexShrink = "0";
    checkbox.checked = isSelected;
    checkbox.disabled = isExisting;
    const nameSpan = item.createEl("span", { text: file.basename });
    nameSpan.style.flex = "1";
    nameSpan.style.overflow = "hidden";
    nameSpan.style.textOverflow = "ellipsis";
    nameSpan.style.whiteSpace = "nowrap";
    if (this.hasSkillProperty(file)) {
      const skillTag = item.createEl("span", { text: "⚡ 已关联技能" });
      skillTag.style.fontSize = "10px";
      skillTag.style.color = "var(--interactive-accent)";
      skillTag.style.background = "rgba(var(--interactive-accent-rgb), 0.12)";
      skillTag.style.padding = "1px 6px";
      skillTag.style.borderRadius = "4px";
      skillTag.style.flexShrink = "0";
    }
    const timeSpan = item.createEl("span", { text: this.formatDate(file.stat.mtime) });
    timeSpan.style.fontSize = "10px";
    timeSpan.style.color = "var(--text-faint)";
    timeSpan.style.flexShrink = "0";
    if (isExisting) {
      item.style.opacity = "0.5";
      const tag = item.createEl("span", { text: "✓ 已添加" });
      tag.style.fontSize = "10px";
      tag.style.color = "var(--text-faint)";
      tag.style.flexShrink = "0";
    }
    const handleSelect = (e) => {
      e.stopPropagation();
      if (isExisting)
        return;
      const isShift = e instanceof MouseEvent && e.shiftKey;
      if (isShift && this.lastClickedPath && this.lastClickedPath !== file.path) {
        const lastIdx = this.currentVisibleFiles.findIndex((f) => f.path === this.lastClickedPath);
        const curIdx = this.currentVisibleFiles.findIndex((f) => f.path === file.path);
        if (lastIdx !== -1 && curIdx !== -1) {
          const start = Math.min(lastIdx, curIdx);
          const end = Math.max(lastIdx, curIdx);
          for (let i = start; i <= end; i++) {
            const f = this.currentVisibleFiles[i];
            if (!existingPaths.has(f.path)) {
              this.selectedPaths.add(f.path);
            }
          }
        }
      } else {
        if (this.selectedPaths.has(file.path)) {
          this.selectedPaths.delete(file.path);
        } else {
          this.selectedPaths.add(file.path);
        }
        this.lastClickedPath = file.path;
      }
      this.renderList(this.searchInput.value.toLowerCase().trim());
    };
    checkbox.addEventListener("change", handleSelect);
    item.addEventListener("click", handleSelect);
    item.addEventListener("mouseenter", () => {
      if (!isExisting && !isSelected) {
        item.style.background = "var(--background-modifier-hover)";
      }
    });
    item.addEventListener("mouseleave", () => {
      if (!isSelected) {
        item.style.background = "";
        item.style.borderLeft = "";
      }
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
